//
// app.post('/image/:userid', async (req, res) => {...});
//
// Uploads an image to the bucket and updates the database,
// returning the asset id assigned to this image.
//
const photoapp_db = require('./photoapp_db.js');
const { PutObjectCommand } = require('@aws-sdk/client-s3');
const { photoapp_s3, s3_bucket_name } = require('./photoapp_s3.js');

const uuid = require('uuid');

exports.post_image = async (req, res) => {
  
  console.log("**Call to post /image/:userid...");

  try {
    const body = req.body; // data => JS object
    const userid = req.params.userid; // Ensure userid is treated as a string
    const { assetname, data: imageData } = body;

    // Log the user ID type and value for debugging
    console.log(`User ID type: ${typeof userid}, value: ${userid}`);

    // Check if the user exists
    const sqlCheckUser = 'SELECT * FROM users WHERE userid = ?';
    const userRows = await new Promise((resolve, reject) => {
      console.log("/image: looking up userid...");
      photoapp_db.query(sqlCheckUser, [userid], (err, rows) => {
        if (err) return reject(err);
        resolve(rows);
      });
    });

    if (userRows.length === 0) {
      console.log("/image no such user...");
      return res.status(400).json({
        "message": "no such user...",
        "assetid": -1
      });
    }

    // The user exists, grab their bucket folder:
    const bucketfolder = userRows[0].bucketfolder;

    // Generate a unique name for the asset:
    const basename = uuid.v4();
    const pos = assetname.lastIndexOf(".");
    const extension = (pos >= 0) ? assetname.substr(pos) : ""; // Grab extension WITH the "."

    const bucketkey = `${bucketfolder}/${basename}${extension}`;

    // Decode the imageData and obtain the raw bytes to send to S3 for storage:
    const bytes = Buffer.from(imageData, 'base64');

    // Upload to S3
    const uploadParams = {
      Bucket: s3_bucket_name,
      Key: bucketkey,
      Body: bytes,
      ContentType: 'image/jpg',
      ACL: 'public-read'
    };

    console.log(`/image: uploading '${assetname}' as '${bucketkey}' to S3...`);
    const command = new PutObjectCommand(uploadParams);
    const s3_response = await photoapp_s3.send(command);

    console.log(`/image uploaded, status code ${s3_response["$metadata"].httpStatusCode}`);

    // Insert asset into the database
    const sqlInsertAsset = 'INSERT INTO assets (userid, assetname, bucketkey) VALUES (?, ?, ?)';
    const insertParams = [userid, assetname, bucketkey];
    const insertResult = await new Promise((resolve, reject) => {
      photoapp_db.query(sqlInsertAsset, insertParams, (err, result) => {
        if (err) return reject(err);
        resolve(result);
      });
    });

    if (insertResult.affectedRows < 1) {
      console.log("/image insert query failed to insert?");
      return res.status(400).json({
        "message": "Internal error, query did not update database?!",
        "userid": -1
      });
    }

    // Success, return asset id that was auto-generated by the database:
    const assetid = insertResult.insertId;

    console.log("/image done, sending response...");
    return res.json({
      "message": "success",
      "assetid": assetid
    });

  } catch (err) {
    console.log("**Error in /image");
    console.error("Error message:", err.message);
    console.error("Error stack:", err.stack); // Log the stack trace for debugging

    return res.status(500).json({
      "message": err.message,
      "assetid": -1
    });
  }
};
